name: Documentation

on:
  schedule:
    # Every hour
    - cron: 0 * * * *
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: pip install --upgrade --upgrade-strategy eager -r requirements.txt
      - name: Fetch documentation
        run: python wiki.py
        env: 
          GITHUB_PAT: ${{ secrets.PAT }}
      - name: Create static build
        run: make html
      - name: Complete static build
        run: |
          touch build/html/.nojekyll
          echo "eagletrt.wiki" > build/html/CNAME
      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build/html
          token: ${{ secrets.PAT }}
